const SWITCH = document.querySelector(".switchdaynight");
const BODY = document.querySelector("body");
const TOPMENU = document.querySelector(".top-menu");
const PARTNER = document.querySelector(".home-partners");
const B01 = document.querySelector("b.plantilla-1");
const H01 = document.querySelector("h1.plantilla-1");
const H02 = document.querySelector("h1.plantilla-2");
const H03 = document.querySelector("h1.plantilla-3");
const H04 = document.querySelector("h1.plantilla-4");
const H05 = document.querySelector("h1.plantilla-5");
const H06 = document.querySelector("h1.plantilla-6");
const H07 = document.querySelector("h1.plantilla-7");
const H08 = document.querySelector("h1.plantilla-8");
const H09 = document.querySelector("h1.plantilla-9");
const H10 = document.querySelector("h1.plantilla-10");
const P01 = document.querySelector("span.plantilla-1");
const P02 = document.querySelector("span.plantilla-2");
const P03 = document.querySelector("span.plantilla-3");
const P04 = document.querySelector("span.plantilla-4");
const P05 = document.querySelector("span.plantilla-5");
const P06 = document.querySelector("span.plantilla-6");
const P07 = document.querySelector("span.plantilla-7");
const P08 = document.querySelector("span.plantilla-8");
const P09 = document.querySelector("span.plantilla-9");
const P10 = document.querySelector("span.plantilla-10");
const STAFFENTRY01 = document.querySelector("div.uno");
const STAFFIMG01 = document.querySelector("a.uno");
const STAFFENTRY02 = document.querySelector("div.dos");
const STAFFIMG02 = document.querySelector("a.dos");
const STAFFENTRY03 = document.querySelector("div.tres");
const STAFFIMG03 = document.querySelector("a.tres");
const STAFFENTRY04 = document.querySelector("div.cuatro");
const STAFFIMG04 = document.querySelector("a.cuatro");
const STAFFENTRY05 = document.querySelector("div.cinco");
const STAFFIMG05 = document.querySelector("a.cinco");
const STAFFENTRY06 = document.querySelector("div.seis");
const STAFFIMG06 = document.querySelector("a.seis");
const STAFFENTRY07 = document.querySelector("div.siete");
const STAFFIMG07 = document.querySelector("a.siete");
const STAFFENTRY08 = document.querySelector("div.ocho");
const STAFFIMG08 = document.querySelector("a.ocho");
const STAFFENTRY09 = document.querySelector("div.nueve");
const STAFFIMG09 = document.querySelector("a.nueve");
const STAFFENTRY10 = document.querySelector("div.diez");
const STAFFIMG10 = document.querySelector("a.diez");

SWITCH.addEventListener( "click", function() {

  if ( this.classList.contains("on") ){
    this.classList.remove("on");
    BODY.classList.remove("on");
    TOPMENU.classList.remove("on");
    PARTNER.classList.remove("on");
    B01.classList.remove("on");
    H01.classList.remove("on");
    H02.classList.remove("on");
    H03.classList.remove("on");
    H04.classList.remove("on");
    H05.classList.remove("on");
    H06.classList.remove("on");
    H07.classList.remove("on");
    H08.classList.remove("on");
    H09.classList.remove("on");
    H10.classList.remove("on");
    P01.classList.remove("on");
    P02.classList.remove("on");
    P03.classList.remove("on");
    P04.classList.remove("on");
    P05.classList.remove("on");
    P06.classList.remove("on");
    P07.classList.remove("on");
    P08.classList.remove("on");
    P09.classList.remove("on");
    P10.classList.remove("on");
    STAFFENTRY01.classList.remove("on");
    STAFFIMG01.classList.remove("on");
    STAFFENTRY02.classList.remove("on");
    STAFFIMG02.classList.remove("on");
    STAFFENTRY03.classList.remove("on");
    STAFFIMG03.classList.remove("on");
    STAFFENTRY04.classList.remove("on");
    STAFFIMG04.classList.remove("on");
    STAFFENTRY05.classList.remove("on");
    STAFFIMG05.classList.remove("on");
    STAFFENTRY06.classList.remove("on");
    STAFFIMG06.classList.remove("on");
    STAFFENTRY07.classList.remove("on");
    STAFFIMG07.classList.remove("on");
    STAFFENTRY08.classList.remove("on");
    STAFFIMG08.classList.remove("on");
    STAFFENTRY09.classList.remove("on");
    STAFFIMG09.classList.remove("on");
    STAFFENTRY10.classList.remove("on");
    STAFFIMG10.classList.remove("on");
  } else {
    this.classList.add("on");
    BODY.classList.add("on");
    TOPMENU.classList.add("on");
    PARTNER.classList.add("on");
    B01.classList.add("on");
    H01.classList.add("on");
    H02.classList.add("on");
    H03.classList.add("on");
    H04.classList.add("on");
    H05.classList.add("on");
    H06.classList.add("on");
    H07.classList.add("on");
    H08.classList.add("on");
    H09.classList.add("on");
    H10.classList.add("on");
    P01.classList.add("on");
    P02.classList.add("on");
    P03.classList.add("on");
    P04.classList.add("on");
    P05.classList.add("on");
    P06.classList.add("on");
    P07.classList.add("on");
    P08.classList.add("on");
    P09.classList.add("on");
    P10.classList.add("on");
    STAFFENTRY01.classList.add("on");
    STAFFIMG01.classList.add("on");
    STAFFENTRY02.classList.add("on");
    STAFFIMG02.classList.add("on");
    STAFFENTRY03.classList.add("on");
    STAFFIMG03.classList.add("on");
    STAFFENTRY04.classList.add("on");
    STAFFIMG04.classList.add("on");
    STAFFENTRY05.classList.add("on");
    STAFFIMG05.classList.add("on");
    STAFFENTRY06.classList.add("on");
    STAFFIMG06.classList.add("on");
    STAFFENTRY07.classList.add("on");
    STAFFIMG07.classList.add("on");
    STAFFENTRY08.classList.add("on");
    STAFFIMG08.classList.add("on");
    STAFFENTRY09.classList.add("on");
    STAFFIMG09.classList.add("on");
    STAFFENTRY10.classList.add("on");
    STAFFIMG10.classList.add("on");
  }
});